### ISSUE TITLE
Not using _imshow_kwargs everywhere in plotting

### ISSUE THREAD

**Issue by Kevin2** [aknierim/thesis_scripts#1]
https://github.com/aknierim/thesis_scripts/blob/244bf4b17aa53350e93ba090a8a9e4e723d75673/thesis_scripts/plotting/skyplots.py#L257

Could you pass the _imshow_kwargs here too? Would make comparison much easier when changing norms etc for I Q U V.

**Comment by aknierim** [comment]
Thanks, I missed that. Will fix that
